name: "New project card"
description: "Use this template for creating new project cards"
title: "[Idea title]"

labels:
  - "Type: New project card"

body:
  - type: markdown
    attributes:
      value: '**Title:**'
  - type: textarea
    id: ideaDescription
    attributes:
      label: "Project description"
      description: "Describe the submitted idea"
    validations:
      required: true
  - type: input
    id: ideaSubmitter
    attributes:
      label: "Idea submitter(s) agency or program:"
      description: "Agency/program of idea submitter(s)"
    validations:
      required: true
  - type: input
    id: slackChannel
    attributes:
      label: "Slack channel:"
      description: "TTS Slack channel where project discussions occur (if known)"
    validations:
      required: false
