name: "New project card template"
description: "Use this template for creating new project cards"
title: "[Idea title]"

labels:
  - "Type: New project card"

body:
  - type: markdown
    attributes:
      value: '**Title:**'
  - type: textarea
    id: ideaDescription
    attributes:
      label: "Project Description"
      description: "Describe the submitted project idea"
    validations:
      required: true
    - type: markdown
    attributes:
      value: '**Project team:**'
  - type: input
    id: ideaAuthor
    attributes:
      label: "Idea author(s):"
      description: "Name/Agency of idea submitter(s)"
    validations:
      required: true
  - type: input
    id: slackChannel
    attributes:
      label: "Slack channel:"
      description: "Channel where project discussions occur (if known)"
    validations:
      required: false