name: "New project card"
description: "Use this template for creating new project cards"
title: "[Idea title]"

labels:
  - "Type: New project card"

body:
  - type: markdown
    attributes:
      value: '**Title:**'
  - type: textarea
    id: ideaDescription
    attributes:
      label: "Project description"
      description: "Describe the submitted idea"
      value: description
      |
      **An idea submitted by civil servants at:** _Agency 1 & Agency 2_"
    validations:
      required: true
